### ISSUE TITLE
Access my subscribed podcasts from another browser?

### ISSUE THREAD

**Issue by Mike20878** [podStation/podStation#336]
I started using Brave, which is based on Chrome.  But I guess it doesn't consider me logged into Google so I can't see my subscribed podcasts.

At least that's how I think it works.  Is there any way to do this or should I just use Chrome for those times I want to use podStation?

Thanks.

**Comment by dellagustin** [comment]
Hello @Mike20878 ,

Thank you for opening this issue.
podStation uses the browser's sync storage for synchronizing data, which means that synchronization cannot, unfortunately, work across browsers, as there is not web standard to this date for cross browser synchronization (that I know of at least).

I have not tested the sync function on Brave, it might work across instances of Brave where you are logged in, but you will have to test that. Please let me know if it works.
If you would like to export your list of subscribed podcasts from one browser, and import it in another one, you can use the export/import OPML function:
![image](https://user-images.githubusercontent.com/260113/183289661-e82ac6f5-a7e5-49e5-93e8-09af30d1c0b5.png)

We do have in our backlog a task to enable synchronization with gPodder services, but that is a long term goal that should not arrive soon (due to other priorities): https://github.com/podStation/podStation/issues/179
I suggest you to subscribe to that other issue.

I'll close this issue, but if you have any other comments or questions, fill free to reopen.
